name: planner
description: An application for planning and tracking both your own holidays,
  and the holidays of your friends.
#Since this is an application that is not published to pub dev, then "publish_to: 'none'".
publish_to: 'none'

# Application version 0.0.0 build 1
version: 0.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true